### PR TITLE
switch use of UNIVERSAL::isa to ref()

### PR DESCRIPTION
**Pull request by karenetheridge**

### CODE REVIEW

**Comment by karenetheridge** [comment]
resolves RT#105948

**Comment by karenetheridge** [comment]
I'm happy to curate this module if you don't have time for it anymore -- it's _very_ useful, and used in some important distributions such as DBIx-Class.

**Comment by chocolateboy** [comment]
Thanks! Released as 0.21.

I've also added you as a co-maintainer of the module on PAUSE and a collaborator on this repo.

**Comment by karenetheridge** [comment]
Awesome, thanks!

**Pull request merged**
